name: Pedro Entringer
description: Um tanto quanto curioso
meta_description: "Pedro Entringer | Developer"

lang: pt-BR
markdown: kramdown
highlighter: rouge

logo: https://www.littlerock.com.br/skin/frontend/mageshop/tema02-skinlittlerock/images/media/logo.png
paginate: 15
baseurl: /
domain_name: 'https://pedroentringer.dev'
google_analytics: 'UA-165073538-1'
plugins: [jekyll-paginate]

permalink: /:categories/:title/

# Details for the RSS feed generator
url:            'https://pedroentringer.dev'
author:         'Pedro Entringer'
